# Generated by Django 3.2.16 on 2022-12-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirebaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100, verbose_name='site')),
                ('apiKey', models.CharField(max_length=100, verbose_name='apiKey')),
                ('authDomain', models.CharField(max_length=250, verbose_name='authDomain')),
                ('databaseURL', models.CharField(max_length=250, verbose_name='databaseURL')),
                ('storageBucket', models.CharField(max_length=250, verbose_name='storageBucket')),
            ],
        ),
    ]
